*;
*MOST FREQUENT VALUE (COUNT);
*;
format IMP_all_day_maintain BEST12.0;
label IMP_all_day_maintain = 'Imputed all_day_maintain';
IMP_all_day_maintain = all_day_maintain;
if missing(all_day_maintain) then IMP_all_day_maintain = 0;
format IMP_closing_at_daily_high BEST12.0;
label IMP_closing_at_daily_high = 'Imputed closing_at_daily_high';
IMP_closing_at_daily_high = closing_at_daily_high;
if missing(closing_at_daily_high) then IMP_closing_at_daily_high = 0;
format IMP_closing_at_daily_low BEST12.0;
label IMP_closing_at_daily_low = 'Imputed closing_at_daily_low';
IMP_closing_at_daily_low = closing_at_daily_low;
if missing(closing_at_daily_low) then IMP_closing_at_daily_low = 0;
format IMP_open_equals_closing BEST12.0;
label IMP_open_equals_closing = 'Imputed open_equals_closing';
IMP_open_equals_closing = open_equals_closing;
if missing(open_equals_closing) then IMP_open_equals_closing = 0;
*;
*CONSTANT VALUE;
*;
