if NAME="all_day_maintain" then do;
ROLE="REJECTED";
LEVEL="BINARY";
ORDER="";
end;
if NAME="closing_at_daily_high" then do;
ROLE="REJECTED";
LEVEL="BINARY";
ORDER="";
end;
if NAME="closing_at_daily_low" then do;
ROLE="REJECTED";
LEVEL="BINARY";
ORDER="";
end;
if NAME="day" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="day_no" then do;
ROLE="REJECTED";
LEVEL="ORDINAL";
ORDER="";
end;
if NAME="month" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="open_equals_closing" then do;
ROLE="REJECTED";
LEVEL="BINARY";
ORDER="";
end;
if NAME="trend" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="year" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
drop DROP;
